//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryEntity
    {
        public CategoryEntity()
        {
            this.Question = new HashSet<QuestionEntity>();
            this.Score = new HashSet<ScoreEntity>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<QuestionEntity> Question { get; set; }
        public virtual ICollection<ScoreEntity> Score { get; set; }
    }
}
