//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuizEntities : DbContext
    {
        public QuizEntities()
            : base("name=QuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<UserEntity> tabUser { get; set; }
        public DbSet<GameTypeEntity> tabGameType { get; set; }
        public DbSet<CategoryEntity> tabCategory { get; set; }
        public DbSet<AnswerEntity> tabAnswer { get; set; }
        public DbSet<QuestionEntity> tabQuestion { get; set; }
        public DbSet<ScoreEntity> tabScore { get; set; }
    }
}
