//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreEntity
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int GameTypeID { get; set; }
        public int CategoryID { get; set; }
        public int Score { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual CategoryEntity Category { get; set; }
        public virtual GameTypeEntity GameType { get; set; }
        public virtual UserEntity User { get; set; }
    }
}
